COMPILER = g++
COMPILER_FLAGS = -Wall -std=c++17
PROGRAM_NAME = sudokuSolver
CPP_FILES = sudokuSolver.cpp 

build:
	$(COMPILER) $(COMPILER_FLAGS) $(CPP_FILES) -o $(PROGRAM_NAME)

run: 
	./$(PROGRAM_NAME)

clean:
	rm -f $(PROGRAM_NAME) *.o